name: Generate SSH key

description: Generate SSH key to access the GH repository

inputs:
  key_name:
    description: Name of the key
    type: string
    required: true
  key_password:
    description: Key password
    type: string
    required: true
  email:
    description: Associated email
    type: string
    required: true
  output_location:
    description: Location to store the generated key
    type: string
    default: /tmp/ssh-keys

outputs:
  repo_key_location:
    description: The created ssh key location
    value: ${{ steps.generate-ssh-key.outputs.key_location }}

runs:
  using: composite
  steps:
    - name: Generate ssh key pair
      id: generate-ssh-key
      shell: bash
      run: |
        EMAIL=${{ inputs.email }}
        KEY_FILE=${{ inputs.output_location }}/${{ inputs.key_name }}

        [ -d ${{ inputs.output_location }} ] && echo "Output directory already exists at ${{ inputs.output_location }}" || {
          echo "Creating output directory at ${{ inputs.output_location }}"
          mkdir -p ${{ inputs.output_location }}
        }

        [ ! -f $KEY_FILE ] && {
          echo "Generating SSH key pair for $EMAIL at $KEY_FILE and password ${{ inputs.key_password }}"
          ssh-keygen -t ed25519 -C "$EMAIL" -f "$KEY_FILE" -P "${{ inputs.key_password }}"
        } || {
          echo "Key file already exists at $KEY_FILE"
        }

        echo "key_location=$KEY_FILE" >> $GITHUB_OUTPUT

