name: Configure ssh accesses
description: Creates the ssh configuration

inputs:
  external_private_key_location:
    description: Full path for directory of private key file to access external git repository 
    required: true
  external_key_file_password:
    description: password for the key file
    required: true
  external_host_config:
    description: external host configuration
    required: true
outputs:
  ssh_config_file:
    description: Location of the ssh configuration file
    value: ${{ steps.ssh-config.outputs.ssh_config_file }}
runs:
  using: composite
  steps:
    - name: Configure SSH
      id: ssh-config
      shell: bash
      run: |
        CONFIG_FILE=/tmp/config

        # Configure the ssh
        cat <<EOF > $CONFIG_FILE
        Host ${{ inputs.external_host_config }}
          AddKeysToAgent yes
          IdentityFile ${{ inputs.external_private_key_location }}
          IgnoreUnknown UseKeychain
        EOF
      
        echo "ssh_config_file=$CONFIG_FILE" >> $GITHUB_OUTPUT 

    - name: Check accesses
      shell: bash
      run: |
        # verify external access
        # ----------------------
        K_FILE=${{ inputs.external_private_key_location }}
        ASK_PASS=/tmp/askpass.sh

        cat <<EOF > $ASK_PASS
        #!/bin/bash
        echo "${{ inputs.external_key_file_password }}"
        EOF

        chmod +x $ASK_PASS

        eval "$(ssh-agent -s)"
        SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$ASK_PASS ssh-add ${{ inputs.external_private_key_location }}

        ssh -T git@${{ inputs.external_host_config }} -F ${{ steps.ssh-config.outputs.ssh_config_file }} -oStrictHostKeyChecking=no
