name: Upload the repository to GH
description: Upload the repository to GH

inputs:
  repo_location:
    description: Full path for directory of the cloned repository
    required: true
  gh_token:
    description: The GitHub token
    required: true

runs:
  using: composite
  steps:
    - name: Configure git repo to GH
      shell: bash
      run: |
        cd ${{ inputs.repo_location }}

        R_BRANCH=$(git branch -a | grep -v 'main' || true)

        [ ! -z "$R_BRANCH" ] && {
          for branch in `echo $R_BRANCH  | sed s,remotes/,,g | xargs`; do
            git checkout -b ${branch#origin/} --track $branch
          done
        }

        REPO_ADDRESS=`echo $new_repo_url | sed -e s,https://,https://${{ inputs.gh_token }}@,g`

        branches=$(git branch | grep -v 'main' | sed 's,*,,g' | xargs || true)

        git remote add upstream $REPO_ADDRESS

        for branch in "main $branches"; do
          git push upstream $branch
        done

        git push --tags upstream
