name: Clone external repository
description: Clone full repo

inputs:
  private_key_location:
    description: Full path for directory of private key to external repo
  host:
    description: Full path for directory of private key file to access GH 
  repository_address:
    description: Full path for directory of private key file to access GH 
    required: true
  key_file_password:
    description: password for the key file
  username:
    description: Username for external repo
  password:
    description: Password for the repo

outputs:
  repo_location:
    description: Location of the cloned repository
    value: ${{ steps.clone-repo.outputs.repo_location }}
  repo_default_branch:
    description: Default branch of the cloned repository
    value: ${{ steps.clone-repo.outputs.repo_default_branch }}

runs:
  using: composite
  steps:
    - name: Configure SSH
      if: ${{ inputs.private_key_location }}
      id: ssh-config
      shell: bash
      run: |
        CONFIG_FILE=/tmp/config

        cat <<EOF >> $CONFIG_FILE
        Host ${{ inputs.host }}
          AddKeysToAgent yes
          IdentityFile ${{ inputs.private_key_location }}
          IgnoreUnknown UseKeychain
        EOF
        
        echo "ssh_config_file=$CONFIG_FILE" >> $GITHUB_OUTPUT 

    - name: Check external repo connection
      shell: bash
      if: ${{ inputs.private_key_location }}
      run: |
        K_FILE=${{ inputs.private_key_location }}

        if [ -z $K_FILE ]; then
          echo "Key file not found: $K_FILE"
          exit 1
        fi
        
        if [ ! -z "${{ inputs.key_file_password }}" ]; then
          ASK_PASS=/tmp/askpass.sh

        cat <<EOF > $ASK_PASS
        #!/bin/bash
        echo "${{ inputs.key_file_password }}"
        EOF

          chmod +x $ASK_PASS

          eval "$(ssh-agent -s)"
          SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$ASK_PASS ssh-add ${{ inputs.private_key_location }}
          echo "ASK_PASS=$ASK_PASS" >> $GITHUB_ENV
        fi

        ssh -T git@${{ inputs.host }} -F ${{ steps.ssh-config.outputs.ssh_config_file }} -oStrictHostKeyChecking=no

    - name: Configure external address
      id: external-address
      shell: bash
      run: |
        if [ ! -z "${{ inputs.private_key_location }}" ]; then
          REPO_ADDRESS=`echo "${{ inputs.repository_address }}"`
        else
          PASS=$(echo "{ \"pass\":\"${{ inputs.password }}\"}" | jq -r '.pass | @uri')
          echo "::add-mask::$PASS"
          REPO_ADDRESS=`echo ${{ inputs.repository_address }} | sed -e s,https://,https://${{ inputs.username }}:$PASS@,g`
        fi
        
        echo "external_repo_url=$REPO_ADDRESS" >> $GITHUB_OUTPUT

    - name: Configure GIT_SSH_COMMAND
      shell: bash
      if: ${{ inputs.private_key_location }}
      run: |
        if [ -z "$ASK_PASS" ]; then
          echo "SSH_ASKPASS not configured"
          git_ssh_cmd="ssh -F ${{ steps.ssh-config.outputs.ssh_config_file }}" 
        else
          echo "SSH_ASKPASS configured"
          git_ssh_cmd="SSH_ASKPASS_REQUIRE=force SSH_ASKPASS=$ASK_PASS ssh -F ${{ steps.ssh-config.outputs.ssh_config_file }}"
        fi

        git config --global core.sshCommand "$git_ssh_cmd"

    - name: Clone external repository
      id: clone-repo
      shell: bash
      run: |
        REPO_ADDRESS=`echo ${{ steps.external-address.outputs.external_repo_url }}`

        echo "Cloning repository: $REPO_ADDRESS"

        [ -d /tmp/external-repo ] && rm -rf /tmp/external-repo

        git clone $REPO_ADDRESS /tmp/external-repo

        cd /tmp/external-repo

        D_BRANCH=$(git symbolic-ref --short HEAD)
       
        cd - > /dev/null 2>&1

        echo "repo_location=/tmp/external-repo" >> $GITHUB_OUTPUT
        echo "repo_default_branch=$D_BRANCH" >> $GITHUB_OUTPUT
