name: Import external repository
run-name: Import 🚀

on:
  workflow_dispatch:
    inputs:
      private_key_location:
        description: Location of the private key to access GH.
        type: string
        required: true
      gh_repo_name:
        description: Name of the new repository
        type: string
        required: true
      gh_repo_owner:
        description: Name of the new repository
        type: string
        default: ${{ github.repository_owner }}
      gh_repo_description:
        description: Description of the new repository
        type: string
        required: true
      external_repo_url:
        description: URL of the external repository
        type: string
        required: true
      external_repo_user:
        description: User to access the external repository
        type: string
        required: true
      external_repo_ssh_key_location:
        description: User to access the external repository
        type: string
        required: true
      external_host:
        description: Full path for directory of private key file to access GH 
        required: true
jobs:
  import-external:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      # - name: Test scripts
      #   run: |
      #     echo "key: [${{ github.repository_owner }}]"

      - name: Terraform Init and Plan
        id: tf-plan
        uses: ./.github/actions/init-terraform
        with:
          tf_state_out: "/tmp/import-tf-state"
          repository_name: ${{ inputs.gh_repo_name }}
          repository_owner: ${{ inputs.gh_repo_owner }}
          gh_token: ${{ secrets.gh_token }}
          gh_repo_description: ${{ inputs.gh_repo_description }}

      - name: Create Repository on GH
        uses: ./.github/actions/create-repo
        with:
          tf_plan: ${{ steps.tf-plan.outputs.tf_plan }}
          tf_out: ${{ steps.tf-plan.outputs.tf_out }}

      - name: Clone external repository
        uses: ./.github/actions/download-external-repo
        id: clone-repo
        with:
          host: ${{ inputs.external_host }}
          repository_address: ${{ inputs.external_repo_url }}
          private_key_location: ${{ inputs.external_repo_ssh_key_location }}
          key_file_password: ${{ secrets.external_repo_ssh_key_password }}

      - name: Upload new repository to GH
        uses: ./.github/actions/upload-repo
        with:
          repo_location: ${{ steps.clone-repo.outputs.repo_location }}
          repository_name: ${{ inputs.gh_repo_name }}
          repository_owner: ${{ inputs.gh_repo_owner }}
          gh_token: ${{ secrets.gh_token }}
